# Site settings
title: ELMO-8
email: elmo-8@mick.twomeylee.name
description: > # this means to ignore newlines until "baseurl:"
  PICO-8 inspired fantasy 8-bit game library for Elm.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elmo-8.twomeylee.name" # the base hostname & protocol for your site
twitter_username: micktwomey
github_username:  micktwomey
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Build settings
markdown: kramdown

gist:
  noscript: false

collections:
  example:
    output: true